//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTechPvtLtd.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FortuneSoftEntities : DbContext
    {
        public FortuneSoftEntities()
            : base("name=FortuneSoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_alerts> tbl_alerts { get; set; }
        public virtual DbSet<tbl_alerts_master> tbl_alerts_master { get; set; }
        public virtual DbSet<tbl_campaign> tbl_campaign { get; set; }
        public virtual DbSet<tbl_customlabel> tbl_customlabel { get; set; }
        public virtual DbSet<tbl_EmailLog> tbl_EmailLog { get; set; }
        public virtual DbSet<tbl_Emailtemp> tbl_Emailtemp { get; set; }
        public virtual DbSet<tbl_EmailtempforAlerts> tbl_EmailtempforAlerts { get; set; }
        public virtual DbSet<tbl_enquirydetails> tbl_enquirydetails { get; set; }
        public virtual DbSet<tbl_EnquiryForm> tbl_EnquiryForm { get; set; }
        public virtual DbSet<tbl_Enquirytracking> tbl_Enquirytracking { get; set; }
        public virtual DbSet<tbl_ErrorLog> tbl_ErrorLog { get; set; }
        public virtual DbSet<tbl_FortuneBasicInfo> tbl_FortuneBasicInfo { get; set; }
        public virtual DbSet<tbl_FortuneRoles> tbl_FortuneRoles { get; set; }
        public virtual DbSet<tbl_FortuneUsers> tbl_FortuneUsers { get; set; }
        public virtual DbSet<tbl_LeadEmailContent> tbl_LeadEmailContent { get; set; }
        public virtual DbSet<tbl_LeadStatus> tbl_LeadStatus { get; set; }
        public virtual DbSet<tbl_LeadStatusEmailContent> tbl_LeadStatusEmailContent { get; set; }
        public virtual DbSet<tbl_Logs> tbl_Logs { get; set; }
        public virtual DbSet<tbl_Menu> tbl_Menu { get; set; }
        public virtual DbSet<tbl_Payment> tbl_Payment { get; set; }
        public virtual DbSet<tbl_Productlist> tbl_Productlist { get; set; }
        public virtual DbSet<tbl_SmsContent> tbl_SmsContent { get; set; }
        public virtual DbSet<tbl_SmsLog> tbl_SmsLog { get; set; }
        public virtual DbSet<tbl_SmsLogForAlerts> tbl_SmsLogForAlerts { get; set; }
        public virtual DbSet<tbl_Smstemp> tbl_Smstemp { get; set; }
        public virtual DbSet<tbl_Source> tbl_Source { get; set; }
        public virtual DbSet<tbl_UserLog> tbl_UserLog { get; set; }
        public virtual DbSet<tbl_Userreports> tbl_Userreports { get; set; }
    }
}
